---
name: Check approval
on:
  merge_group:
permissions: {}
jobs:
  foo:
    timeout-minutes: 10
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - run: ":"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
  check-approval:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: suzuki-shunsuke/deny-self-approve-action@9ee0a3ee1ed44415a065b05291560487c7847db3 # v0.2.0
