---
name: Check approval
on:
  merge_group:
permissions: {}
jobs:
  foo:
    timeout-minutes: 10
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - run: ":"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
  check-approval:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: suzuki-shunsuke/deny-self-approve-action@f7d3981afcc79c85290b20502c6a4e532417ce7d # v0.1.2
