---
name: test merge_group
on:
  merge_group: {}
jobs:
  foo:
    timeout-minutes: 10
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - run: ":"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
