---
name: test merge_group
on:
  pull_request:
  merge_group:
jobs:
  foo:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_EVENT_NAME"
      - run: echo "$GITHUB_REF"
      - run: echo "$GITHUB_HEAD_REF"
      - run: echo "$GITHUB_REF_NAME"
      - run: echo "$GITHUB_SHA"
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{toJson(github)}}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
      - run: go run main.go
