---
name: Test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  foo:
    timeout-minutes: 10
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - run: ":"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
  validate-pr-review:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      pull-requests: read # To get pull requests
      contents: read # To get pull request commits
    steps:
      - uses: suzuki-shunsuke/validate-pr-review-action@bd967a12742566a5e3fb02878e4e2447da68f72e # v0.0.4

