---
name: Test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  foo:
    timeout-minutes: 10
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - run: ":"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
